name: legal_ease_app
description: LegalEase - frontend-only Flutter app example.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.9.0'
  flutter: '>=3.19.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.0.0
  flutter_svg: ^2.0.7
  fl_chart: ^0.68.0
  http: ^1.2.2
  url_launcher: ^6.3.0
  supabase_flutter: ^2.0.0
  flutter_dotenv: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/gavel.png
    - assets/civil.png
    - assets/criminal.png
    - assets/pi.png
    - assets/taxation.png
    - assets/business.png
    - .env

